// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS0SggiaEB61WiKbI20nbI7k5ZsnV0_XM',
    appId: '1:871225930361:android:566662c78b6ff23a931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGE0Z1cKJa3hJ8CyKAadd28dcFcVCWOI',
    appId: '1:871225930361:ios:b469bd4dc05f9327931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.firebasestorage.app',
    androidClientId: '871225930361-b4au5v3tkjqmgrencu5p2e2lkeutsfhr.apps.googleusercontent.com',
    iosBundleId: 'jp.ami.elan',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrSCTp_oXY2ybz9G0SAcw7NbbTeFPx3pU',
    appId: '1:871225930361:web:6d53f05259b66ccc931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    authDomain: 'frinurse.firebaseapp.com',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.firebasestorage.app',
    measurementId: 'G-5V63QWGGDM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGE0Z1cKJa3hJ8CyKAadd28dcFcVCWOI',
    appId: '1:871225930361:ios:b469bd4dc05f9327931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.firebasestorage.app',
    androidClientId: '871225930361-b4au5v3tkjqmgrencu5p2e2lkeutsfhr.apps.googleusercontent.com',
    iosBundleId: 'jp.ami.elan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrSCTp_oXY2ybz9G0SAcw7NbbTeFPx3pU',
    appId: '1:871225930361:web:6d53f05259b66ccc931aa8',
    messagingSenderId: '871225930361',
    projectId: 'frinurse',
    authDomain: 'frinurse.firebaseapp.com',
    databaseURL: 'https://frinurse.firebaseio.com',
    storageBucket: 'frinurse.firebasestorage.app',
    measurementId: 'G-5V63QWGGDM',
  );

}